import React, { useState, useEffect, useRef } from 'react'
import { Upload, Play, CheckCircle, Clock, Download, X, AlertCircle, RefreshCw } from 'lucide-react'
import toast from 'react-hot-toast'
import Papa from 'papaparse'
import { startBatchJob, getBatchStatus, listBatchJobs, isBackendOnline } from '../services/api'

const DEMO_JOBS = [
  { id: 'demo1', name: 'Q1 Donor Reports 2024', status: 'done', progress: 100, total: 120, done: 120, audience: 'Donors', tone: 'Emotional', sector: 'Education', startedAt: new Date(Date.now()-172800000).toISOString(), completedAt: new Date(Date.now()-172000000).toISOString() },
  { id: 'demo2', name: 'CSR Impact Pack 2023', status: 'done', progress: 100, total: 300, done: 300, audience: 'Donors', tone: 'Emotional', sector: 'Environment', startedAt: new Date(Date.now()-432000000).toISOString(), completedAt: new Date(Date.now()-431000000).toISOString() },
]

export default function Batch() {
  const [liveJobs, setLiveJobs] = useState([])
  const [backendOnline, setBackendOnline] = useState(null)
  const [form, setForm] = useState({ name: '', audience: 'Donors', tone: 'Emotional & Inspiring', sector: 'Education', count: 10 })
  const [file, setFile] = useState(null)
  const [dragover, setDragover] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const pollRef = useRef({})
  const set = (k, v) => setForm(f => ({ ...f, [k]: v }))

  useEffect(() => {
    isBackendOnline().then(online => {
      setBackendOnline(online)
      if (online) refreshJobs()
    })
    return () => Object.values(pollRef.current).forEach(clearInterval)
  }, [])

  const refreshJobs = async () => {
    try {
      const res = await listBatchJobs()
      if (res.success) setLiveJobs(res.jobs)
    } catch {}
  }

  const pollJob = (jobId) => {
    if (pollRef.current[jobId]) return
    pollRef.current[jobId] = setInterval(async () => {
      try {
        const res = await getBatchStatus(jobId)
        if (res.success) {
          setLiveJobs(prev => {
            const idx = prev.findIndex(j => j.id === jobId)
            if (idx === -1) return [...prev, res.job]
            const updated = [...prev]
            updated[idx] = res.job
            return updated
          })
          if (res.job.status === 'done' || res.job.status === 'failed') {
            clearInterval(pollRef.current[jobId])
            delete pollRef.current[jobId]
            if (res.job.status === 'done') toast.success(`"${res.job.name}" complete! ${res.job.total} stories generated.`)
          }
        }
      } catch {}
    }, 2000)
  }

  const handleFile = (f) => {
    if (!f) return
    if (f.name.endsWith('.csv')) {
      Papa.parse(f, {
        complete: (r) => {
          setFile({ name: f.name, size: f.size, rows: r.data.length, rawFile: f })
          set('count', r.data.length)
          toast.success(`${f.name} — ${r.data.length} records detected`)
        },
        header: true, skipEmptyLines: true
      })
    } else {
      setFile({ name: f.name, size: f.size, rows: form.count, rawFile: f })
      toast.success(`${f.name} uploaded`)
    }
  }

  const handleStartJob = async () => {
    if (!form.name.trim()) { toast.error('Please enter a job name'); return }
    if (!backendOnline) { toast.error('Backend not running. Start it with: cd server && npm run dev'); return }
    setSubmitting(true)
    try {
      const count = parseInt(form.count) || 10
      const res = await startBatchJob(
        file?.rawFile || null,
        { name: form.name, audience: form.audience, tone: form.tone, sector: form.sector, count }
      )
      if (res.success) {
        toast.success(`Batch job "${form.name}" started — ${res.total} stories queued`)
        setForm(f => ({ ...f, name: '' }))
        setFile(null)
        const newJob = {
          id: res.jobId, name: form.name, status: 'running',
          progress: 0, total: res.total, done: 0,
          audience: form.audience, tone: form.tone.split(' ')[0], sector: form.sector,
          startedAt: new Date().toISOString()
        }
        setLiveJobs(prev => [newJob, ...prev])
        pollJob(res.jobId)
      }
    } catch (err) {
      toast.error(err.message || 'Failed to start batch job')
    } finally {
      setSubmitting(false)
    }
  }

  const downloadJob = (job) => {
    const content = [
      `${job.name} — Batch Export`,
      `Generated: ${job.total} stories | Audience: ${job.audience} | Sector: ${job.sector}`,
      `Completed: ${job.completedAt ? new Date(job.completedAt).toLocaleString() : 'N/A'}`,
      `Generated by NarrAIte — AI Impact Narrative Generator`,
      '',
      '='.repeat(60),
      '',
      ...(job.results || []).map((r, i) => [
        `Story ${i + 1}: ${r.title || 'Impact Narrative'}`,
        '-'.repeat(40),
        r.story || r.text || '',
        r.keyQuote ? `\nKey Quote: "${r.keyQuote}"` : '',
        '',
      ].join('\n'))
    ].join('\n')
    const blob = new Blob([content || `${job.name} — ${job.total} stories generated`], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = job.name.replace(/\s/g, '_') + '_export.txt'
    a.click()
    toast.success(`Downloading ${job.total} stories…`)
  }

  const allJobs = [...liveJobs, ...DEMO_JOBS.filter(d => !liveJobs.find(l => l.id === d.id))]
  const running = allJobs.filter(j => j.status === 'running')
  const done = allJobs.filter(j => j.status === 'done')

  const timeAgo = (iso) => {
    if (!iso) return 'just now'
    const diff = Date.now() - new Date(iso).getTime()
    if (diff < 60000) return 'just now'
    if (diff < 3600000) return Math.floor(diff/60000) + ' min ago'
    if (diff < 86400000) return Math.floor(diff/3600000) + ' hr ago'
    return Math.floor(diff/86400000) + ' days ago'
  }

  return (
    <div className="animate-slide-up">
      <div style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12 }}>
          <div>
            <h2 className="font-display" style={{ fontSize: 26 }}>Batch Processing</h2>
            <p style={{ fontSize: 14, color: 'var(--ink3)', marginTop: 4 }}>Generate hundreds of personalized stories from a single dataset</p>
          </div>
          {backendOnline !== null && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '6px 14px', borderRadius: 20, fontSize: 12, fontWeight: 500, background: backendOnline ? 'var(--accentL)' : '#FEE2E2', color: backendOnline ? 'var(--accent)' : '#991B1B', border: `1px solid ${backendOnline ? 'rgba(82,183,136,0.3)' : '#FECACA'}` }}>
              {backendOnline ? '✅ Backend Online' : '❌ Backend Offline'}
            </div>
          )}
        </div>
      </div>

      {/* Stats */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 16, marginBottom: 24 }}>
        {[
          { label: 'Total Jobs', value: allJobs.length },
          { label: 'Running', value: running.length, color: '#B45309' },
          { label: 'Completed', value: done.length, color: '#16a34a' },
          { label: 'Stories Generated', value: done.reduce((a, j) => a + (j.total || 0), 0) },
        ].map((s, i) => (
          <div key={i} className="stat-card">
            <div style={{ fontSize: 11, color: 'var(--ink4)', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 8 }}>{s.label}</div>
            <div className="font-display" style={{ fontSize: 30, color: s.color || 'var(--ink)' }}>{s.value}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '420px 1fr', gap: 20 }}>
        {/* New Job Form */}
        <div className="card">
          <div className="font-display" style={{ fontSize: 17, marginBottom: 18 }}>New Batch Job</div>

          {!backendOnline && backendOnline !== null && (
            <div style={{ background: '#FEF3C7', border: '1px solid #FCD34D', borderRadius: 10, padding: '12px 14px', marginBottom: 16, fontSize: 12, color: '#92400E', display: 'flex', gap: 8 }}>
              <AlertCircle size={15} style={{ flexShrink: 0, marginTop: 1 }} />
              <span>Start backend first: <code style={{ background: 'rgba(0,0,0,0.1)', padding: '1px 6px', borderRadius: 4 }}>cd server && npm run dev</code></span>
            </div>
          )}

          <div style={{ marginBottom: 14 }}>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 500, color: 'var(--ink2)', marginBottom: 6 }}>Job Name *</label>
            <input className="form-input" value={form.name} onChange={e => set('name', e.target.value)} placeholder="e.g. Q2 2024 Donor Impact Reports" />
          </div>

          <div style={{ marginBottom: 14 }}>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 500, color: 'var(--ink2)', marginBottom: 6 }}>Upload Dataset (optional)</label>
            <div
              className={`upload-zone${dragover ? ' dragover' : ''}`}
              style={{ padding: 24 }}
              onClick={() => document.getElementById('batch-file-in').click()}
              onDragOver={e => { e.preventDefault(); setDragover(true) }}
              onDragLeave={() => setDragover(false)}
              onDrop={e => { e.preventDefault(); setDragover(false); handleFile(e.dataTransfer.files[0]) }}>
              <Upload size={24} color="var(--ink4)" style={{ marginBottom: 8 }} />
              <div style={{ fontSize: 13, color: 'var(--ink2)', marginBottom: 3, fontWeight: 500 }}>Upload CSV or Excel</div>
              <div style={{ fontSize: 11, color: 'var(--ink4)' }}>Each row = one personalized story</div>
              <input type="file" id="batch-file-in" style={{ display: 'none' }} accept=".csv,.xlsx,.xls" onChange={e => handleFile(e.target.files[0])} />
            </div>
            {file && (
              <div style={{ marginTop: 8, padding: '10px 12px', background: 'var(--accentL)', borderRadius: 8, display: 'flex', alignItems: 'center', gap: 10, fontSize: 12 }}>
                <span>📄</span>
                <div style={{ flex: 1 }}>
                  <strong>{file.name}</strong>
                  {file.rows && <span style={{ color: 'var(--accent)', marginLeft: 8 }}>{file.rows} records detected</span>}
                </div>
                <button onClick={() => setFile(null)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink4)' }}><X size={13} /></button>
              </div>
            )}
            <button className="btn btn-ghost btn-sm" style={{ marginTop: 8, fontSize: 12, color: 'var(--accent)', gap: 6 }}
              onClick={() => {
                const csv = 'organization,beneficiary,metrics,challenge,solution,location,period\nAsha Foundation,"500 children","Dropout -40%, 12 classrooms",Poverty,Mobile classrooms,Mumbai,2024\nChandni Health,"10000 patients","22000 consultations",Poor access,Mobile clinics,Delhi,2024'
                const blob = new Blob([csv], { type: 'text/csv' })
                const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'narraite_batch_template.csv'; a.click()
                toast.success('Template downloaded!')
              }}>
              <Download size={12} /> Download CSV template
            </button>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 14 }}>
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 500, color: 'var(--ink2)', marginBottom: 6 }}>Audience</label>
              <select className="form-select" value={form.audience} onChange={e => set('audience', e.target.value)}>
                {['Donors', 'Investors', 'NGOs', 'Students', 'Healthcare', 'Government'].map(a => <option key={a}>{a}</option>)}
              </select>
            </div>
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 500, color: 'var(--ink2)', marginBottom: 6 }}>Tone</label>
              <select className="form-select" value={form.tone} onChange={e => set('tone', e.target.value)}>
                {['Emotional & Inspiring', 'Data-driven & Analytical', 'Formal & Professional', 'Conversational & Warm'].map(t => <option key={t}>{t}</option>)}
              </select>
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 20 }}>
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 500, color: 'var(--ink2)', marginBottom: 6 }}>Sector</label>
              <select className="form-select" value={form.sector} onChange={e => set('sector', e.target.value)}>
                {['Education', 'Healthcare', 'Environment', 'Women Empowerment', 'Livelihood', 'Other'].map(s => <option key={s}>{s}</option>)}
              </select>
            </div>
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 500, color: 'var(--ink2)', marginBottom: 6 }}>Records to process</label>
              <input className="form-input" type="number" value={form.count} onChange={e => set('count', e.target.value)} min="1" max="50" />
              <div style={{ fontSize: 10, color: 'var(--ink4)', marginTop: 3 }}>Max 50 per job (API limits)</div>
            </div>
          </div>

          <button className="btn btn-primary" onClick={handleStartJob} disabled={submitting}
            style={{ width: '100%', justifyContent: 'center', gap: 8, opacity: submitting ? 0.8 : 1 }}>
            {submitting ? <><span className="spinner" style={{ width: 14, height: 14 }} /> Starting…</> : <><Play size={14} /> Start Batch Job</>}
          </button>

          <div style={{ marginTop: 14, padding: 12, background: 'var(--cream2)', borderRadius: 10, fontSize: 12, color: 'var(--ink3)', lineHeight: 1.6 }}>
            💡 <strong style={{ color: 'var(--ink2)' }}>How it works:</strong> Upload CSV where each row is a beneficiary/project. NarrAIte sends each row to the AI and generates a unique story. Results are saved to your Story Library automatically.
          </div>
        </div>

        {/* Jobs Panel */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {/* Running */}
          {running.length > 0 && (
            <div className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
                <div className="font-display" style={{ fontSize: 17 }}>Active Jobs</div>
                <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                  <span style={{ fontSize: 11, padding: '4px 10px', borderRadius: 20, background: '#FEF3C7', color: '#B45309', fontWeight: 600 }}>{running.length} running</span>
                  <button className="btn btn-ghost btn-sm" onClick={refreshJobs} style={{ padding: '4px 8px' }}><RefreshCw size={12} /></button>
                </div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                {running.map(j => (
                  <div key={j.id} style={{ padding: '14px 16px', background: 'var(--cream2)', borderRadius: 12, border: '1px solid var(--border)' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 }}>
                      <div>
                        <div style={{ fontSize: 14, fontWeight: 500 }}>{j.name}</div>
                        <div style={{ fontSize: 11, color: 'var(--ink4)', marginTop: 2 }}>
                          {j.audience} · {j.tone} · {j.sector} · Started {timeAgo(j.startedAt)}
                        </div>
                      </div>
                      <div style={{ textAlign: 'right' }}>
                        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--accent)' }}>{j.done}/{j.total}</div>
                        <div style={{ fontSize: 10, color: 'var(--ink4)' }}>stories</div>
                      </div>
                    </div>
                    <div className="progress-bar"><div className="progress-fill" style={{ width: (j.progress || 0) + '%' }} /></div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 6 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                        <Clock size={11} color="var(--ink4)" />
                        <span style={{ fontSize: 11, color: 'var(--ink4)' }}>Processing via AI…</span>
                      </div>
                      <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--accent)' }}>{j.progress || 0}%</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Completed */}
          <div className="card">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
              <div className="font-display" style={{ fontSize: 17 }}>Completed Jobs</div>
              <span style={{ fontSize: 11, padding: '4px 10px', borderRadius: 20, background: 'var(--accentL)', color: 'var(--accent)', fontWeight: 600 }}>{done.length} completed</span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {done.map((j, i) => (
                <div key={j.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 14px', borderRadius: 10, background: i % 2 === 0 ? 'var(--cream2)' : 'transparent', gap: 12 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <CheckCircle size={15} color="#16a34a" style={{ flexShrink: 0 }} />
                    <div>
                      <div style={{ fontSize: 13, fontWeight: 500 }}>{j.name}</div>
                      <div style={{ fontSize: 11, color: 'var(--ink4)' }}>
                        {j.total} stories · {j.audience} · {timeAgo(j.completedAt || j.startedAt)}
                        {j.errors > 0 && <span style={{ color: '#B45309', marginLeft: 8 }}>({j.errors} errors)</span>}
                      </div>
                    </div>
                  </div>
                  <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                    <span style={{ fontSize: 10, padding: '2px 8px', borderRadius: 20, background: 'var(--accentL)', color: 'var(--accent)', fontWeight: 600 }}>Done</span>
                    <button className="btn btn-outline btn-sm" onClick={() => downloadJob(j)} style={{ gap: 5 }}>
                      <Download size={12} /> Export
                    </button>
                  </div>
                </div>
              ))}
              {done.length === 0 && (
                <div style={{ textAlign: 'center', padding: '32px 16px', color: 'var(--ink4)', fontSize: 13 }}>
                  No completed jobs yet. Start your first batch job!
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
