import React from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, FileText } from 'lucide-react'

export default function Terms() {
  return (
    <div style={{ background: 'var(--cream)', minHeight: '100vh' }}>
      {/* NAV */}
      <nav style={{
        position: 'sticky', top: 0, zIndex: 100,
        background: 'rgba(250,250,247,0.92)', backdropFilter: 'blur(16px)',
        borderBottom: '1px solid var(--border)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0 24px', height: 60
      }}>
        <Link to="/" className="font-display" style={{ fontSize: 22, letterSpacing: '-0.5px', textDecoration: 'none', color: 'var(--ink)' }}>
          Narr<span style={{ color: 'var(--accent3)' }}>AI</span>te
        </Link>
        <Link to="/" className="btn btn-ghost btn-sm" style={{ display: 'flex', alignItems: 'center', gap: 6, textDecoration: 'none' }}>
          <ArrowLeft size={14}/> Back to Home
        </Link>
      </nav>

      {/* CONTENT */}
      <div style={{ maxWidth: 720, margin: '0 auto', padding: 'clamp(40px, 6vw, 80px) 24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 32 }}>
          <div style={{
            width: 48, height: 48, borderRadius: 14,
            background: 'var(--accentL)', display: 'flex', alignItems: 'center', justifyContent: 'center',
            color: 'var(--accent)'
          }}>
            <FileText size={24}/>
          </div>
          <div>
            <h1 className="font-display" style={{ fontSize: 32, letterSpacing: '-0.8px', margin: 0 }}>Terms of Service</h1>
            <p style={{ fontSize: 13, color: 'var(--ink4)', margin: '4px 0 0' }}>Last updated: May 2025</p>
          </div>
        </div>

        <div className="card" style={{ lineHeight: 1.8, fontSize: 14, color: 'var(--ink2)' }}>
          <h2 style={{ fontSize: 18, color: 'var(--ink)', marginBottom: 12 }}>1. Acceptance of Terms</h2>
          <p style={{ marginBottom: 20 }}>
            By accessing and using NarrAIte, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
          </p>

          <h2 style={{ fontSize: 18, color: 'var(--ink)', marginBottom: 12 }}>2. Description of Service</h2>
          <p style={{ marginBottom: 20 }}>
            NarrAIte is an AI-powered platform that transforms structured impact data into personalized, emotionally resonant narratives for various audiences including donors, investors, NGOs, healthcare providers, and government bodies.
          </p>

          <h2 style={{ fontSize: 18, color: 'var(--ink)', marginBottom: 12 }}>3. User Responsibilities</h2>
          <p style={{ marginBottom: 20 }}>
            You are responsible for the accuracy of the data you provide. You agree not to upload misleading, false, or harmful content. You retain ownership of your original data and the narratives generated from it.
          </p>

          <h2 style={{ fontSize: 18, color: 'var(--ink)', marginBottom: 12 }}>4. Intellectual Property</h2>
          <p style={{ marginBottom: 20 }}>
            The NarrAIte platform, including its design, features, and code, is the intellectual property of its creators. Stories generated through the platform using your data belong to you and may be used freely for your organizational purposes.
          </p>

          <h2 style={{ fontSize: 18, color: 'var(--ink)', marginBottom: 12 }}>5. Limitation of Liability</h2>
          <p style={{ marginBottom: 20 }}>
            NarrAIte is provided "as is" without any warranties, express or implied. We are not liable for any damages arising from the use or inability to use the service, including but not limited to inaccuracies in AI-generated content.
          </p>

          <h2 style={{ fontSize: 18, color: 'var(--ink)', marginBottom: 12 }}>6. AI-Generated Content</h2>
          <p style={{ marginBottom: 20 }}>
            Content generated by NarrAIte is created using artificial intelligence and should be reviewed before publication. We recommend verifying all facts, statistics, and claims in generated narratives against your original data.
          </p>

          <h2 style={{ fontSize: 18, color: 'var(--ink)', marginBottom: 12 }}>7. Modifications to Terms</h2>
          <p style={{ marginBottom: 20 }}>
            We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the updated terms.
          </p>

          <h2 style={{ fontSize: 18, color: 'var(--ink)', marginBottom: 12 }}>8. Contact</h2>
          <p>
            For questions about these Terms of Service, please contact us at{' '}
            <a href="mailto:anushkatiwariofficial@gmail.com" style={{ color: 'var(--accent3)', fontWeight: 500 }}>
              anushkatiwariofficial@gmail.com
            </a>
          </p>
        </div>
      </div>

      {/* FOOTER */}
      <footer style={{ background: 'var(--ink)', borderTop: '1px solid rgba(255,255,255,0.06)', padding: '24px clamp(20px, 5vw, 40px)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 14 }}>
          <div className="font-display" style={{ fontSize: 18, color: '#fff' }}>
            Narr<span style={{ color: 'var(--accent3)' }}>AI</span>te
          </div>
          <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.25)' }}>
            Built with ❤️ by Anushka Tiwari
          </div>
          <div style={{ display: 'flex', gap: 18 }}>
            <Link to="/privacy" style={{ fontSize: 12, color: 'rgba(255,255,255,0.35)', textDecoration: 'none' }}>Privacy</Link>
            <Link to="/terms" style={{ fontSize: 12, color: 'rgba(255,255,255,0.55)', textDecoration: 'none', fontWeight: 500 }}>Terms</Link>
            <Link to="/contact" style={{ fontSize: 12, color: 'rgba(255,255,255,0.35)', textDecoration: 'none' }}>Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
